#!/bin/bash
#  Version 2015.05.07  
#  This bash script is used to sort segy file that generated by REF2SEGY
#  Wangsheng
#  2015-05-07

Pendulum="9EA1 9F47 9FDA 9F40 911E 9FDE 9EE4 9F58 912A"
i=1
while [[ $i -le 9 ]];
do
	PEND=`echo $Pendulum | awk -F' ' '{print $'$i'}'`
	echo $PEND
	rm SEGY_$PEND -r
	mkdir SEGY_$PEND
	for DIR in `ls R1* -d`;do
		echo $DIR
		cp $DIR/*$PEND* SEGY_$PEND/
	done 
	i=`expr $i + 1`
done