#!/bin/bash
#  Version 2015.05.07  
#  This bash script is used to sort segy file that generated by REF2SEGY
#  Wangsheng
#  2015-05-07
#
#  Version 2015.05.08
#  Add getopts(-D -P -V) functions.
#  Wangsheng
#  2015-05-08
#
#  Version 2015.05.09
#  Delete (-P), add (-S)
#  Wangsheng
#  2015-05-08

HMSG="Usage: SH_SortSegy.sh -D Directory -S String [-V]"
VERBOSE=" > /dev/null"
while  getopts  "D:S:V "  arg #选项后面的冒号表示该选项需要参数
do
         case  $arg  in
             D)
                DIR=$OPTARG
                #echo \# Directory: $DIR
                ;;
             S)
                STR=$OPTARG
                ;;
             V)
				VERBOSE=""
				;;
             ?)  #当有不认识的选项的时候arg为 ?
            	#echo  " unkonw argument "
        		exit  1
                ;;
        esac
done
if [[ -z $DIR ]] || [[ -z $STR ]]; then
	echo $HMSG
	exit 1
fi

NUM=`echo $STR | awk  '{print NF}'` #Number of Keywords

ln -s $DIR ./TMP
#STR="9EA1 9F47 9FDA 9F40 911E 9FDE 9EE4 9F58 912A"
i=1
while [[ $i -le $NUM ]];
do
    KEYWORDS=`echo $STR | awk -F' ' '{print $'$i'}'`
    if [[ -a SEGY_$KEYWORDS ]]; then
        rm SEGY_$KEYWORDS/*
    else
        mkdir SEGY_$KEYWORDS
    fi
    echo "echo $i $KEYWORDS" | sh
    i=`expr $i + 1`

    cp TMP/R*/*$KEYWORDS* SEGY_$KEYWORDS/
done

rm TMP -r