#!/bin/bash
#  Version 2015.05.07  
#  This bash script is used to sort segy file that generated by REF2SEGY
#  Wangsheng
#  2015-05-07
#
#  Version 2015.05.08
#  Add getopts(-D -P -V) functions.
#  Wangsheng
#  2015-05-08
HMSG="Usage: SH_SORTSEGY.sh -D Directory -P PendulumCodes [-V]"
VERBOSE=" > /dev/null"
while  getopts  " D:P:V "  arg #选项后面的冒号表示该选项需要参数
do
         case  $arg  in
             D)
                DIR=$OPTARG
                #echo \# Directory: $DIR
                ;;
             P)
                Pendulum=$OPTARG
                ;;
             V)
				VERBOSE=""
				;;
             ?)  #当有不认识的选项的时候arg为 ?
            	echo  " unkonw argument "
        		exit  1
        ;;
        esac
done
if [[ -z $DIR ]] || [[ -z $Pendulum ]]; then
	echo $HMSG
	exit 1
fi
NUM=`echo $Pendulum | awk  '{print NF}'` #Number of Pendulums
#echo $Pendulum
#Pendulum="9EA1 9F47 9FDA 9F40 911E 9FDE 9EE4 9F58 912A"
i=1
while [[ $i -le $NUM ]];
do
	PEND=`echo $Pendulum | awk -F' ' '{print $'$i'}'`
	rm SEGY_$PEND -r
	mkdir SEGY_$PEND
	for SUBDIR in `ls $DIR/R* -d`;do
		echo "echo $i $PEND $DIR/$SUBDIR$VERBOSE" | sh
		cp $DIR/$SUBDIR/*$PEND* SEGY_$PEND/
	done
	i=`expr $i + 1`
done